
##################
### HOW TO USE ###
##################

# Set Working directory to folder containing csv files. 
# These files can be generated by dumping the db into csv.
# First dump the database as is to obtain the original items.csv and feedbacks.csv
# After that, run biggest_seller.sql and then dump items.csv and feedbacks.csv again to obtain the state after targeted intervention.
# You can then use the functions below to plot the graphs, of course you have to adjust the import csv lines to get either PRE or POST intervention.


### General statements

library(ggplot2)
library(ggthemes)
library(extrafont)
library(plyr)
library(scales)


# Import csv files
items <- read.csv("items.csv")
feedbacks <- read.csv("feedbacks.csv")


# Set constants

# All markets
marketplaces <- c("Alphabay", "Silk Road 1", "Evolution", "Black Market Reloaded", "Agora", "Pandora", "Hydra", "Silk Road 2")

# Markets with feedback_value
marketplaces2 <- c("Silk Road 1", "Evolution", "Agora", "Pandora", "Hydra")

# colors
cols <- c("red", "green", "yellow", "blue", "orange", "purple", "cyan", "magenta", "darkolivegreen1", "pink", "aquamarine4", "lavender", "brown", "beige", "maroon", "aquamarine", "darkolivegreen", "burlywood1", "navy", "grey", "black")



############################################
### Graph Total turnover per marketplace ###
############################################

# Set data frame for ouput
out <- data.frame(matrix(ncol = 3, nrow = 0))
x <- c("date", "marketplace", "order_amount")
colnames(out) <- x

# iterate over mps
for (mp in marketplaces) {
  if (mp != "") {
    print(mp)
    
    # Get all feedbacks for current mp
    orders <- subset(feedbacks, marketplace == mp)
    
    # Rip out days
    orders$date <- format(as.Date(orders$date), "%Y-%m")
    
    # Dates
    dates <- orders$date
    
    # Unique dates
    unique_dates <- unique(orders$date)
    
    # Turnover
    turnover <- orders$order_amount_usd
    
    # DF with only categories, dates & amounts
    df <- data.frame(date = dates, category=orders$category, order_amount = turnover)
    
    #out <- data.frame(matrix(ncol = 3, nrow = 0))
    #x <- c("date", "marketplace", "order_amount")
    #colnames(out) <- x
    
    # Loop over all unique dates
    for (dt in unique_dates) {
      # Get all feedbacks with current date
      tmp <- subset(df, date == dt)
      
      # Amount of feedbacks
      length_tmp <- nrow(tmp)
      
      # Sum all amounts, leading to 1 entry
      tmp <- ddply(tmp,"date", numcolwise(sum))
      
      # Divide by 1000 readability
      tmp$order_amount <- tmp$order_amount / 1000
      
      # Store mp
      tmp$marketplace <- mp
      
      # Set to middle of month
      tmp$date <- paste(dt, "15", sep="-")
      
      # Store
      out <- rbind(out, tmp)
    }
  }
}

# Sort on date
out$date <- as.Date(out$date)
out <- out[order(out$date),]

# Plot
ggplot(data=out, aes(x=date, order_amount, group=marketplace)) + 
  geom_line(aes(color = marketplace, linetype = marketplace)) + 
  scale_x_date(date_breaks = "1 year", labels = date_format("%Y")) +
  labs(x = "Date (Month)", y = "Turnover (1000 USD)") + 
  theme_minimal() + 
  theme(plot.title = element_text(hjust = 0.5))

 

#############################################################
### Average turnover with Total feedback per vendor       ###
#############################################################

# The .csv files can be dumped from the database after running biggest_seller.sql
# And then you can plot each market by changing feedback_turnover <- read.csv("<MarketName>_feedback_turnover.csv")

library(ggpubr)
feedback_turnover <- read.csv("Agora_feedback_turnover.csv")

ggscatter(feedback_turnover, x = "feedback_value", y = "avg_turnover", color="red",
          add = "reg.line",  add.params = list(color = "blue"), 
          cor.coef = TRUE, cor.method = "spearman", size = 1, cor.coeff.args = list(method = "spearman", label.x = 1000, label.sep = "\n"),
          xlab = "Total feedback per vendor", ylab = "Average turnover (USD)")
